Repository prisms-center/phaseField, pull requests merged in 2024-10, with the labels that each got.

#247 Update automatic test script
  tests/automatic_tests/CHAC_anisotropyRegularized/CMakeLists.txt
  tests/automatic_tests/CHAC_anisotropyRegularized/ICs_and_BCs.cc
  tests/automatic_tests/CHAC_anisotropyRegularized/customPDE.h
  tests/automatic_tests/CHAC_anisotropyRegularized/equations.cc
  tests/automatic_tests/CHAC_anisotropyRegularized/gold_integratedFields.txt
  tests/automatic_tests/CHAC_anisotropyRegularized/main.cc
  tests/automatic_tests/CHAC_anisotropyRegularized/parameters.prm
  tests/automatic_tests/CHAC_anisotropyRegularized/postprocess.cc
  tests/automatic_tests/allenCahn/CMakeLists.txt
  tests/automatic_tests/allenCahn/ICs_and_BCs.cc
  tests/automatic_tests/allenCahn/customPDE.h
  tests/automatic_tests/allenCahn/equations.cc
  tests/automatic_tests/allenCahn/gold_integratedFields.txt
  tests/automatic_tests/allenCahn/main.cc
  tests/automatic_tests/allenCahn/parameters.prm
  tests/automatic_tests/allenCahn/postprocess.cc
  tests/automatic_tests/cahnHilliard/CMakeLists.txt
  tests/automatic_tests/cahnHilliard/ICs_and_BCs.cc
  tests/automatic_tests/cahnHilliard/customPDE.h
  tests/automatic_tests/cahnHilliard/equations.cc
  tests/automatic_tests/cahnHilliard/gold_integratedFields.txt
  tests/automatic_tests/cahnHilliard/main.cc
  tests/automatic_tests/cahnHilliard/parameters.prm
  tests/automatic_tests/cahnHilliard/postprocess.cc
  tests/automatic_tests/coupledCahnHilliardAllenCahn/CMakeLists.txt
  tests/automatic_tests/coupledCahnHilliardAllenCahn/ICs_and_BCs.cc
  tests/automatic_tests/coupledCahnHilliardAllenCahn/customPDE.h
  tests/automatic_tests/coupledCahnHilliardAllenCahn/equations.cc
  tests/automatic_tests/coupledCahnHilliardAllenCahn/gold_integratedFields.txt
  tests/automatic_tests/coupledCahnHilliardAllenCahn/main.cc
  tests/automatic_tests/coupledCahnHilliardAllenCahn/parameters.prm
  tests/automatic_tests/coupledCahnHilliardAllenCahn/postprocess.cc
  tests/automatic_tests/precipitateEvolution/CMakeLists.txt
  tests/automatic_tests/precipitateEvolution/ICs_and_BCs.cc
  tests/automatic_tests/precipitateEvolution/customPDE.h
  tests/automatic_tests/precipitateEvolution/equations.cc
  tests/automatic_tests/precipitateEvolution/gold_integratedFields.txt
  tests/automatic_tests/precipitateEvolution/main.cc
  tests/automatic_tests/precipitateEvolution/parameters.prm
  tests/automatic_tests/precipitateEvolution/postprocess.cc
  tests/automatic_tests/run_automatic_tests.py
  tests/automatic_tests/test_CHAC_anisotropyRegularized/integratedFields.txt
  tests/automatic_tests/test_coupledCahnHilliardAllenCahn/integratedFields.txt
  tests/automatic_tests/test_precipitateEvolution/integratedFields.txt
  tests/automatic_tests/test_results.txt
  tests/unit_tests/unit_test_results.txt
Labels: enhancement

#249 Clang tidy fixes
  .clang-tidy
  .gitignore
  CMakeLists.txt
  include/EquationDependencyParser.h
  include/IntegrationTools/pfield/Mesh.hh
  include/SimplifiedGrainRepresentation.h
  include/inputFileReader.h
  include/matrixFreePDE.h
  include/sortIndexEntryPairList.h
  include/userInputParameters.h
  src/EquationDependencyParser/EquationDependencyParser.cc
  src/OrderParameterRemapper/OrderParameterRemapper.cc
  src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.cc
  src/inputFileReader/inputFileReader.cc
  src/matrixfree/boundaryConditions.cc
  src/matrixfree/checkpoint.cc
  src/matrixfree/initForTests.cc
  src/matrixfree/initialConditions.cc
  src/matrixfree/invM.cc
  src/matrixfree/matrixFreePDE.cc
  src/matrixfree/nucleation.cc
  src/matrixfree/outputResults.cc
  src/models/mechanics/computeStress.h
  src/pFunction/pFunction.h
  src/parallelNucleationList/parallelNucleationList.cc
  src/userInputParameters/load_BC_list.cc
  src/userInputParameters/load_user_constants.cc
  src/userInputParameters/setTimeStepList.cc
  src/userInputParameters/userInputParameters.cc
  src/utilities/sortIndexEntryPairList.cc
  src/utilities/vectorBCFunction.cc
  src/variableAttributeLoader/variableAttributeLoader.cc
  src/variableContainer/variableContainer.cc
Labels: Type: Error handling

#222 optimize vtk file read-in behavior
  src/matrixfree/initialConditions.cc
Labels: Type: Feature, Type: Refactor

#256 Fixed incomplete refactoring of methods in customPDE override
  applications/allenCahn_conserved/customPDE.h
Labels: Type: Bug

#245 Adding script to check that all applications work
  .gitignore
  applications/CHiMaD_benchmarks/CHiMaD_benchmark6a/submit_mpi.pbs
  applications/CHiMaD_benchmarks/CHiMaD_benchmark6b/customPDE.h
  applications/CHiMaD_benchmarks/CHiMaD_benchmark6b/parameters.prm
  applications/CHiMaD_benchmarks/CHiMaD_benchmark6b/submit_mpi.pbs
  applications/fickianDiffusion/integratedFields.txt
  applications/grainGrowth/integratedFields.txt
  applications/precipitateEvolution_pfunction/integratedFields.txt
  applications/steadyStateAllenCahn/CMakeLists.txt
  applications/steadyStateAllenCahn/ICs_and_BCs.cc
  applications/steadyStateAllenCahn/customPDE.h
  applications/steadyStateAllenCahn/equations.cc
  applications/steadyStateAllenCahn/formulation_allenCahn.pdf
  applications/steadyStateAllenCahn/parameters.prm
  applications/steadyStateAllenCahn/tex_files/allenCahn.tex
  src/inputFileReader/inputFileReader.cc
  src/matrixfree/AdaptiveRefinement.cc
  src/matrixfree/computeLHS.cc
  src/userInputParameters/setTimeStepList.cc
  tests/automatic_tests/application_debug_test.py
Labels: Status: ⚠ High Priority

#260 Fixed log spacing
  src/userInputParameters/setTimeStepList.cc
Labels: Type: Bug, Type: Refactor

#262 Adding assertions for model constants
  include/userInputParameters.h
Labels: Type: Error handling

#264 Rename point variable in grain growth application
  applications/grainGrowth/ICs_and_BCs.cc
Labels: Status: ⚠ High Priority, Type: Refactor

#263 Switch to Allen-Cahn documentation to markdown
  applications/allenCahn/allenCahn.md
  applications/allenCahn/allenCahn.pdf
  applications/allenCahn/tex_files/allenCahn.tex
Labels: Documentation: General

#265 Refactor linear/nonlinear solves in `solveIncrement.cc`
  applications/allenCahn_conserved/customPDE.h
  include/matrixFreePDE.h
  src/matrixfree/solveIncrement.cc
Labels: Type: Refactor

#268 Support for `IMPLICIT_TIME_DEPENDENT` equation types & Advection application
  applications/advection/CMakeLists.txt
  applications/advection/ICs_and_BCs.cc
  applications/advection/advection.md
  applications/advection/customPDE.h
  applications/advection/equations.cc
  applications/advection/parameters.prm
  include/EquationDependencyParser.h
  include/matrixFreePDE.h
  include/model_variables.h
  include/userInputParameters.h
  include/variableContainer.h
  src/EquationDependencyParser/EquationDependencyParser.cc
  src/matrixfree/computeLHS.cc
  src/matrixfree/computeRHS.cc
  src/matrixfree/init.cc
  src/matrixfree/invM.cc
  src/matrixfree/postprocessor.cc
  src/matrixfree/reinit.cc
  src/matrixfree/solveIncrement.cc
  src/userInputParameters/loadVariableAttributes.cc
  src/variableContainer/variableContainer.cc
Labels: Type: Feature, Status: ⚠ Medium Priority

#275 Pinning linear solves
  include/matrixFreePDE.h
  include/userInputParameters.h
  src/inputFileReader/inputFileReader.cc
  src/matrixfree/boundaryConditions.cc
  src/matrixfree/init.cc
  src/matrixfree/reinit.cc
  src/userInputParameters/userInputParameters.cc
  tests/unit_tests/main.cc
  tests/unit_tests/test_setRigidBodyModeConstraints.h
  tests/unit_tests/unitTest.h
  tests/unit_tests/unit_test_results.txt
Labels: Type: Bug, Status: ⚠ High Priority

#278 Adding linux CI timeout
  .github/workflows/linux.yml
Labels: Type: Bug, Status: ⚠ Medium Priority
