Repository prisms-center/phaseField, pull requests merged in 2024-11, with the labels that each got.

#315 Updating `CMakeLists.txt`
  .github/workflows/clang-format.yml
  .github/workflows/linux.yml
  .gitignore
  CMakeLists.txt
  README.md
  VERSION
  applications/CHAC_anisotropy/CMakeLists.txt
  applications/CHAC_anisotropyRegularized/CMakeLists.txt
  applications/CHAC_performance_test/CMakeLists.txt
  applications/CHiMaD_benchmarks/CHiMaD_benchmark1a/CMakeLists.txt
  applications/CHiMaD_benchmarks/CHiMaD_benchmark1b/CMakeLists.txt
  applications/CHiMaD_benchmarks/CHiMaD_benchmark1c/CMakeLists.txt
  applications/CHiMaD_benchmarks/CHiMaD_benchmark2a/CMakeLists.txt
  applications/CHiMaD_benchmarks/CHiMaD_benchmark3a/CMakeLists.txt
  applications/CHiMaD_benchmarks/CHiMaD_benchmark6a/CMakeLists.txt
  applications/CHiMaD_benchmarks/CHiMaD_benchmark6b/CMakeLists.txt
  applications/CHiMaD_benchmarks/CHiMaD_benchmark7a/CMakeLists.txt
  applications/MgNd_precipitate_single_Bppp/CMakeLists.txt
  applications/allenCahn/CMakeLists.txt
  applications/allenCahn_conserved/CMakeLists.txt
  applications/alloySolidification/CMakeLists.txt
  applications/alloySolidification_uniform/CMakeLists.txt
  applications/anisotropyFacet/CMakeLists.txt
  applications/cahnHilliard/CMakeLists.txt
  applications/corrosion/CMakeLists.txt
  applications/corrosion_microgalvanic/CMakeLists.txt
  applications/coupledCahnHilliardAllenCahn/CMakeLists.txt
  applications/dendriticSolidification/CMakeLists.txt
  applications/eshelbyInclusion/CMakeLists.txt
  applications/fickianDiffusion/CMakeLists.txt
  applications/grainGrowth/CMakeLists.txt
  applications/grainGrowth_dream3d/CMakeLists.txt
  applications/mechanics/CMakeLists.txt
  applications/nucleationModel/CMakeLists.txt
  applications/nucleationModel_preferential/CMakeLists.txt
  applications/precipitateEvolution/CMakeLists.txt
  applications/precipitateEvolution_pfunction/CMakeLists.txt
  applications/spinodalDecomposition/CMakeLists.txt
  contrib/catch/catch.hpp
  include/config.h.in
  tests/automatic_tests/CHAC_anisotropyRegularized/CMakeLists.txt
  tests/automatic_tests/allenCahn/CMakeLists.txt
  tests/automatic_tests/allenCahn/main.cc
  tests/automatic_tests/application_debug_test.py
  tests/automatic_tests/cahnHilliard/CMakeLists.txt
  tests/automatic_tests/cahnHilliard/main.cc
  tests/automatic_tests/coupledCahnHilliardAllenCahn/CMakeLists.txt
  tests/automatic_tests/coupledCahnHilliardAllenCahn/main.cc
  tests/automatic_tests/main.cc
  tests/automatic_tests/precipitateEvolution/CMakeLists.txt
  tests/automatic_tests/precipitateEvolution/main.cc
  tests/automatic_tests/run_automatic_tests.py
  tests/unit_tests/boundaryConditions.cc
  tests/unit_tests/initialConditions.cc
  tests/unit_tests/main.cc
  version
Labels: Type: Error handling

#303 Refactored variableAttributeLoader
  applications/allenCahn_conserved/customPDE.h
  include/EquationDependencyParser.h
  include/inputFileReader.h
  include/sortIndexEntryPairList.h
  include/userInputParameters.h
  include/varTypeEnums.h
  include/variableAttributeLoader.h
  include/variableAttributes.h
  src/EquationDependencyParser/EquationDependencyParser.cc
  src/inputFileReader/inputFileReader.cc
  src/matrixfree/boundaryConditions.cc
  src/matrixfree/buildFields.cc
  src/matrixfree/checkpoint.cc
  src/matrixfree/init.cc
  src/matrixfree/initialConditions.cc
  src/matrixfree/outputResults.cc
  src/matrixfree/reassignGrains.cc
  src/matrixfree/reinit.cc
  src/matrixfree/setNonlinearEqInitialGuess.cc
  src/matrixfree/solveIncrement.cc
  src/userInputParameters/loadVariableAttributes.cc
  src/userInputParameters/userInputParameters.cc
  src/utilities/sortIndexEntryPairList.cc
  src/variableAttributeLoader/variableAttributeLoader.cc
  src/variableAttributes/variableAttributes.cc
  tests/unit_tests/main.cc
  tests/unit_tests/test_EquationDependencyParser.h
  tests/unit_tests/test_setOutputTimeSteps.h
  tests/unit_tests/unitTest.h
  tests/unit_tests/unit_test_results.txt
Labels: Status: ⚠ High Priority, Status: Needs testing, Status: Needs review

#321 initialize num_pp_vars which gets printed during initialization
  src/inputFileReader/inputFileReader.cc
Labels: Type: Bug, Status: ⚠ Low Priority
