Repository prisms-center/phaseField, pull requests merged in 2024-12, with the labels that each got.

#333 Adding pr template
  .github/pull_request_template.md
Labels: Documentation: General, Status: ⚠ High Priority

#343 fixed nonlinearity criterion
  src/variableAttributes/variableAttributes.cc
Labels: Type: Bug, Status: ⚠ High Priority, Status: Needs testing, Status: Needs review

#362 Updated dead deal.II download link
  doc/doxygen/user_manual/installation/install_prereqs.md
Labels: Documentation: Website

#360 Field unit tests
  .github/workflows/linux.yml
  include/core/fields.h
  tests/CMakeLists.txt
  tests/core/fields.cc
Labels: Type: Error handling, Status: Needs review

#367 Adding contrib.rocks
  README.md
  authors
Labels: Documentation: General, Status: Needs review

#369 adding optional caliper dependency
  CMakeLists.txt
  include/config.h.in
Labels: Type: Feature

#371 Insert dependencies
  include/core/variableAttributeLoader.h
  src/core/variableAttributeLoader.cc
Labels: Type: Feature, Status: ⚠ Low Priority

#372 Virtualize user-facing variableAttributeLoader functions
  include/core/variableAttributeLoader.h
Labels: Status: ⚠ Medium Priority
