Repository prisms-center/phaseField, pull requests merged in 2024-09, with the labels that each got.

#226 Switching to `dealii::EvaluationFlags` for deal.II 9.6.0 Compatibility
  include/EquationDependencyParser.h
  include/matrixFreePDE.h
  include/model_variables.h
  include/variableContainer.h
  src/EquationDependencyParser/EquationDependencyParser.cc
  src/matrixfree/computeIntegral.cc
  src/matrixfree/init.cc
  src/matrixfree/invM.cc
  src/matrixfree/matrixFreePDE.cc
  src/matrixfree/setNonlinearEqInitialGuess.cc
  src/userInputParameters/loadVariableAttributes.cc
  src/variableContainer/variableContainer.cc
  tests/unit_tests/test_EquationDependencyParser.h
Labels: enhancement, refactoring

#230 GitHub actions
  .github/workflows/clang-format.yml
  .github/workflows/linux.yml
  .travis.yml
  README.md
  tests/automatic_tests/run_automatic_tests.py
Labels: enhancement, ⚠ High Priority

#224 Fixed FloodFiller unit test and fixed grainGrowth bug
  include/FloodFiller.h
  src/FloodFiller/FloodFiller.cc
  src/matrixfree/initialConditions.cc
  src/matrixfree/reassignGrains.cc
  tests/unit_tests/test_FloodFiller.h
  tests/unit_tests/test_OrderParameterRemapper.h
Labels: bug

#234 Deleting deprecated apps
  applications/_allenCahn_implicit/CMakeLists.txt
  applications/_allenCahn_implicit/ICs_and_BCs.h
  applications/_allenCahn_implicit/customPDE.h
  applications/_allenCahn_implicit/equations.h
  applications/_allenCahn_implicit/formulation_allenCahn.pdf
  applications/_allenCahn_implicit/main.cc
  applications/_allenCahn_implicit/parameters.prm
  applications/_allenCahn_implicit/postprocess.h
  applications/_allenCahn_implicit/tex_files/allenCahn.tex
  applications/_nucleating_precipitates_MgRE/CMakeLists.txt
  applications/_nucleating_precipitates_MgRE/ICs_and_BCs.h
  applications/_nucleating_precipitates_MgRE/customPDE.h
  applications/_nucleating_precipitates_MgRE/equations.h
  applications/_nucleating_precipitates_MgRE/main.cc
  applications/_nucleating_precipitates_MgRE/nucleation.h
  applications/_nucleating_precipitates_MgRE/parameters.prm
  applications/_nucleating_precipitates_MgRE/postprocess.h
Labels: documentation

#241 Fix multiple linear/nonlinear solves
  include/model_variables.h
  include/variableContainer.h
  src/matrixfree/computeLHS.cc
  src/userInputParameters/loadVariableAttributes.cc
  src/variableContainer/variableContainer.cc
Labels: bug, enhancement
