Repository prisms-center/phaseField, pull requests merged in 2025-05, with the labels that each got.

#535 make IC functions members of PDEoperator
  applications/_MgNd_precipitate_single_Bppp/custom_pde.h
  applications/_precipitate_evolution/ICs_and_BCs.cc
  applications/_precipitate_evolution/custom_pde.h
  applications/allen_cahn_explicit/ICs_and_BCs.cc
  applications/allen_cahn_explicit/custom_pde.h
  applications/eshelby_inclusion/ICs_and_BCs.cc
  applications/eshelby_inclusion/custom_pde.h
  include/prismspf/core/initial_conditions.h
  include/prismspf/core/pde_operator.h
  include/prismspf/solvers/explicit_base.h
  include/prismspf/solvers/nonexplicit_base.h
  src/core/initial_conditions.cc
  src/solvers/explicit_base.cc
  src/solvers/nonexplicit_base.cc
  tests/automatic_tests/allen_cahn_explicit/ICs_and_BCs.cc
  tests/automatic_tests/allen_cahn_explicit/custom_pde.h
  tests/automatic_tests/allen_cahn_implicit/ICs_and_BCs.cc
  tests/automatic_tests/allen_cahn_implicit/custom_pde.h
  tests/automatic_tests/blank/ICs_and_BCs.cc
  tests/automatic_tests/blank/custom_pde.h
  tests/automatic_tests/cahn_hilliard_explicit/ICs_and_BCs.cc
  tests/automatic_tests/cahn_hilliard_explicit/custom_pde.h
  tests/automatic_tests/fracture/ICs_and_BCs.cc
  tests/automatic_tests/fracture/custom_pde.h
  tests/automatic_tests/heat_equation_steady_state/ICs_and_BCs.cc
  tests/automatic_tests/heat_equation_steady_state/custom_pde.h
  tests/automatic_tests/mechanics/ICs_and_BCs.cc
  tests/automatic_tests/mechanics/custom_pde.h
  tests/automatic_tests/precipitate_explicit/ICs_and_BCs.cc
  tests/automatic_tests/precipitate_explicit/custom_pde.h
  tests/performance_tests/allen_cahn/custom_pde.h
Labels: Type: Feature, 3.0

#542 Making nonuniform boundary conditions part of customPDE
  applications/allen_cahn_explicit/ICs_and_BCs.cc
  applications/allen_cahn_explicit/custom_pde.h
  applications/eshelby_inclusion/ICs_and_BCs.cc
  applications/eshelby_inclusion/custom_pde.h
  include/prismspf/core/constraint_handler.h
  include/prismspf/core/nonuniform_dirichlet.h
  include/prismspf/core/pde_operator.h
  include/prismspf/core/pde_problem.h
  include/prismspf/solvers/explicit_base.h
  include/prismspf/solvers/explicit_constant_solver.h
  include/prismspf/solvers/explicit_postprocess_solver.h
  include/prismspf/solvers/explicit_solver.h
  include/prismspf/solvers/linear_solver_base.h
  include/prismspf/solvers/linear_solver_gmg.h
  include/prismspf/solvers/linear_solver_identity.h
  include/prismspf/solvers/nonexplicit_auxiliary_solver.h
  include/prismspf/solvers/nonexplicit_base.h
  include/prismspf/solvers/nonexplicit_linear_solver.h
  include/prismspf/solvers/nonexplicit_self_nonlinear_solver.h
  src/core/constraint_handler.cc
  src/core/nonuniform_dirichlet.cc
  src/core/pde_problem.cc
  src/solvers/explicit_base.cc
  src/solvers/explicit_constant_solver.cc
  src/solvers/explicit_postprocess_solver.cc
  src/solvers/explicit_solver.cc
  src/solvers/linear_solver_base.cc
  src/solvers/linear_solver_gmg.cc
  src/solvers/linear_solver_identity.cc
  src/solvers/nonexplicit_auxiliary_solver.cc
  src/solvers/nonexplicit_base.cc
  src/solvers/nonexplicit_linear_solver.cc
  src/solvers/nonexplicit_self_nonlinear_solver.cc
  tests/automatic_tests/allen_cahn_explicit/ICs_and_BCs.cc
  tests/automatic_tests/allen_cahn_explicit/custom_pde.h
  tests/automatic_tests/allen_cahn_implicit/ICs_and_BCs.cc
  tests/automatic_tests/allen_cahn_implicit/custom_pde.h
  tests/automatic_tests/blank/ICs_and_BCs.cc
  tests/automatic_tests/blank/custom_pde.h
  tests/automatic_tests/cahn_hilliard_explicit/ICs_and_BCs.cc
  tests/automatic_tests/cahn_hilliard_explicit/custom_pde.h
  tests/automatic_tests/fracture/ICs_and_BCs.cc
  tests/automatic_tests/fracture/custom_pde.h
  tests/automatic_tests/heat_equation_steady_state/ICs_and_BCs.cc
  tests/automatic_tests/heat_equation_steady_state/custom_pde.h
  tests/automatic_tests/mechanics/ICs_and_BCs.cc
  tests/automatic_tests/mechanics/custom_pde.h
  tests/automatic_tests/precipitate_explicit/ICs_and_BCs.cc
  tests/automatic_tests/precipitate_explicit/custom_pde.h
  tests/performance_tests/allen_cahn/custom_pde.h
Labels: 3.0

#544 Fix typos
  applications/_MgNd_precipitate_single_Bppp/precipitateEvolution_KKS.md
  applications/_grainGrowth/grainGrowth.md
  applications/_grainGrowth_dream3d/grainGrowth.md
Labels: Documentation: General, 3.0

#545 Updating run-clang-tidy to 20
  .github/workflows/clang-tidy.yml
  .github/workflows/compile_applications.yml
  contrib/utilities/clang_tidy.sh
Labels: 3.0

#557 Remove quotes from reference to userInputs.output_file_type
  src/core/outputResults.cc
Labels: Status: Good first issue
