Repository prisms-center/phaseField, pull requests merged in 2025-01, with the labels that each got.

#375 Reorganize inputFileReader and userInputParameters
  include/core/inputFileReader.h
  include/core/userInputParameters.h
  src/core/inputFileReader.cc
  src/core/userInputParameters.cc
Labels: Type: Refactor, Status: ⚠ Low Priority

#383 Helper function for converting `std::vector` into `Tensor<VectorizedArray> `
  include/core/matrixFreePDE.h
  include/core/refinement/AdaptiveRefinement.h
  include/core/typeDefs.h
  include/core/variableContainer.h
  include/grains/FloodFiller.h
  include/grains/OrderParameterRemapper.h
  include/utilities/utilities.h
  src/core/checkpoint.cc
  src/core/init.cc
  src/core/initial_conditions/initialConditions.cc
  src/core/outputResults.cc
  src/core/postprocessing/computeIntegral.cc
  src/core/postprocessing/postprocessor.cc
  src/core/refinement/AdaptiveRefinement.cc
  src/core/reinit.cc
  src/core/solvers/computeLHS.cc
  src/core/solvers/computeRHS.cc
  src/core/solvers/setNonlinearEqInitialGuess.cc
  src/core/solvers/solveIncrement.cc
  src/core/variableContainer.cc
  src/grains/FloodFiller.cc
  src/grains/OrderParameterRemapper.cc
Labels: Type: Feature

#385 Updating nonlinear printing info
  applications/allenCahn_conserved/customPDE.h
  include/core/matrixFreePDE.h
  src/core/invM.cc
  src/core/solvers/solveIncrement.cc
Labels: Type: Bug, Type: Error handling

#387 Custom exceptions
  applications/CHiMaD_benchmarks/CHiMaD_benchmark1c/customPDE.h
  applications/CHiMaD_benchmarks/CHiMaD_benchmark6b/customPDE.h
  applications/allenCahn_conserved/customPDE.h
  include/core/boundary_conditions/nonUniformDirichletBC.h
  include/core/exceptions.h
  include/core/initial_conditions/initialConditions.h
  include/core/matrixFreePDE.h
  include/core/userInputParameters.h
  include/core/variableContainer.h
  include/core/variableValueContainer.h
  include/field_input/IntegrationTools/pfield/Mesh.hh
  include/field_input/IntegrationTools/pfield/interpolation/Interpolator.hh
  include/grains/OrderParameterRemapper.h
  include/utilities/utilities.h
  src/core/checkpoint.cc
  src/core/initial_conditions/initialConditions.cc
  src/core/inputFileReader.cc
  src/core/outputResults.cc
  src/core/solvers/solveIncrement.cc
  src/core/userInputParameters.cc
  src/core/variableAttributeLoader.cc
  src/core/variableContainer.cc
  src/grains/FloodFiller.cc
  src/grains/OrderParameterRemapper.cc
  src/grains/reassignGrains.cc
Labels: Type: Error handling

#397 Converted CHAC and MgNd Precipitation documentation to markdown
  applications/CHAC_anisotropy/CHAC_anisotropy.md
  applications/CHAC_anisotropy/CHAC_anisotropy.pdf
  applications/CHAC_anisotropy/tex_files/CHAC_anisotropy.tex
  applications/CHAC_anisotropyRegularized/CHAC_anisotropyRegularized.md
  applications/CHAC_anisotropyRegularized/CHAC_anisotropyRegularized.pdf
  applications/CHAC_anisotropyRegularized/tex_files/CHAC_anisotropyRegularized.tex
  applications/CHAC_performance_test/formulation_coupledCHAC.md
  applications/CHAC_performance_test/formulation_coupledCHAC.pdf
  applications/CHAC_performance_test/tex_files/coupledCHAC.tex
  applications/MgNd_precipitate_single_Bppp/precipitateEvolution_KKS.md
  applications/MgNd_precipitate_single_Bppp/precipitateEvolution_KKS.pdf
  applications/MgNd_precipitate_single_Bppp/tex_files/precipitateEvolution_KKS.pdf
  applications/MgNd_precipitate_single_Bppp/tex_files/precipitateEvolution_KKS.tex
Labels: Documentation: General

#421 Added template instantiations for vector, set, list of inserted dependencies
  include/core/variableAttributeLoader.h
  src/core/variableAttributeLoader.cc
Labels: Type: Feature
